language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI server home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - sudo mkdir -p before-deploy
  - pwd
  - sudo cp scripts/deploy.sh before-deploy/
  - sudo cp appspec.yml before-deploy/
  - sudo cp build/libs/*.jar before-deploy/
  - sudo cd before-deploy
  - sudo zip -r before-deploy *
  - cd ../
  - sudo mkdir -p deploy
  - sudo mv before-deploy/before-deploy.zip deploy/sijangtong-server.zip

    #  - zip -r sijangtong-server *
    #  - mkdir -p deploy
    #  - mv sijangtong-server.zip deploy/sijangtong-server.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # from Travis repo setting
    secret_access_key: $AWS_SECRET_KEY # from Travis repo
    bucket: jinho-webserver-build # S3 bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # access zip file private
    local_dir: deploy # dir made before deploy
    wait-until-deployed: true
    on: 
      all_branches: true # permit all branches

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jinho-webserver-build # s3 bucket
    key: sijangtong-server.zip
    bundle_type: zip
    application: jinho-webservice-ec2
    deployment_group: jinho-webservice-ec2-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true

# notificate by email
notifications: 
  email:
    recipients:
      - dlwlsgh4687@gmail.com
